name: Auto Update Shariah Database

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # এখানে v4 করা হয়েছে

    - name: Set up Python
      uses: actions/setup-python@v5 # এখানে v5 করা হয়েছে
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Updater Script
      run: python updater.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.json
        git commit -m "Auto-updated Shariah Data" || exit 0
        git push
